/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const gigs = [
  {
    id: 1,
    title: "Build a high-converting landing page for a SaaS product",
    category: "Web Development",
    budget: 15000,
    experienceLevel: "Intermediate",
    description: "We are launching a new AI-powered productivity tool and need a modern, high-converting landing page. The design should be minimalist yet impactful. You will be responsible for the front-end implementation using React and Tailwind CSS. We have the wireframes ready, but we need you to bring them to life with smooth animations (using Framer Motion) and responsive design. Integration with a waitlist form (via Mailchimp or similar) is required. Performance optimization is a top priority.",
    postedDate: "2026-03-01",
    clientName: "Rajesh Kumar",
    clientCompany: "FlowState AI",
    clientType: "Startup",
    clientRating: 4.8,
    location: "Remote"
  },
  {
    id: 2,
    title: "Brand identity and logo design for a fitness startup",
    category: "Design",
    budget: 8000,
    experienceLevel: "Beginner",
    description: "We are starting a new boutique gym chain called 'Pulse' and need a fresh brand identity. This includes a primary logo, secondary logo, color palette, and typography guidelines. The vibe should be energetic, modern, and high-end. We want something that stands out on gym apparel and digital platforms. You should provide the final assets in SVG, PNG, and AI formats. A brief brand style guide (PDF) is also expected.",
    postedDate: "2026-03-05",
    clientName: "Priya Sharma",
    clientCompany: "Pulse Fitness",
    clientType: "Startup",
    clientRating: 4.5,
    location: "Andheri West, Mumbai, India"
  },
  {
    id: 3,
    title: "Technical content writer for AI and ML blog",
    category: "Writing",
    budget: 5000,
    experienceLevel: "Intermediate",
    description: "Seeking a knowledgeable writer to produce 4 high-quality articles per month for our tech blog. Topics will range from Generative AI trends to practical tutorials on Machine Learning using Python. Each article should be approximately 1200-1500 words, SEO-optimized, and include relevant code snippets or diagrams where necessary. You should have a solid understanding of current AI technologies and be able to explain complex concepts to a semi-technical audience.",
    postedDate: "2026-03-08",
    clientName: "Amit Patel",
    clientCompany: "TechInsights Media",
    clientType: "Agency",
    clientRating: 4.9,
    location: "Remote"
  },
  {
    id: 4,
    title: "Expert React Native developer for e-commerce scaling",
    category: "Mobile Dev",
    budget: 45000,
    experienceLevel: "Expert",
    description: "Our e-commerce platform is growing rapidly, and we need an expert React Native developer to help us scale our mobile application. You will be working on implementing complex features like real-time inventory tracking, personalized recommendations, and a seamless multi-step checkout process. Deep experience with Redux Toolkit, performance profiling, and native module integration is required. You will also be responsible for ensuring the app maintains a 99.9% crash-free rate.",
    postedDate: "2026-03-10",
    clientName: "Sanjay Gupta",
    clientCompany: "ShopSwift Global",
    clientType: "Enterprise",
    clientRating: 4.7,
    location: "Indiranagar, Bangalore, India"
  },
  {
    id: 5,
    title: "Growth-focused Social Media Marketing Manager",
    category: "Marketing",
    budget: 12000,
    experienceLevel: "Intermediate",
    description: "We need a creative and data-driven Social Media Manager to take over our Instagram, LinkedIn, and Twitter presence. Your goal is to increase organic engagement and drive traffic to our website. Responsibilities include creating a monthly content calendar, designing basic graphics (Canva is fine), writing compelling captions, and managing community interactions. You should also have experience running small-scale paid ad campaigns with a focus on ROI.",
    postedDate: "2026-03-11",
    clientName: "Ananya Iyer",
    clientCompany: "Bloom Cosmetics",
    clientType: "Startup",
    clientRating: 4.6,
    location: "Remote"
  },
  {
    id: 6,
    title: "Full-stack Engineer for Custom Enterprise CRM",
    category: "Web Development",
    budget: 50000,
    experienceLevel: "Expert",
    description: "We are looking for a seasoned Full-stack Developer to lead the development of a custom CRM tailored for the real estate industry. The system needs to handle lead management, automated follow-ups, and detailed reporting dashboards. The tech stack is MERN (MongoDB, Express, React, Node.js). You should be comfortable designing database schemas, implementing secure authentication (JWT/OAuth), and building complex UI components. This is a long-term project with potential for ongoing maintenance.",
    postedDate: "2026-03-02",
    clientName: "Vikram Singh",
    clientCompany: "Elite Realty Solutions",
    clientType: "Enterprise",
    clientRating: 5.0,
    location: "Connaught Place, Delhi, India"
  },
  {
    id: 7,
    title: "Senior UI/UX Designer for Fintech Dashboard",
    category: "Design",
    budget: 25000,
    experienceLevel: "Intermediate",
    description: "Design a comprehensive, user-friendly dashboard for a new wealth management platform. The focus is on simplifying complex financial data through intuitive visualizations and a clean interface. You will be responsible for user research, wireframing, and high-fidelity prototyping in Figma. The design must be fully responsive and adhere to accessibility standards (WCAG). Experience in the fintech space is a significant advantage.",
    postedDate: "2026-03-04",
    clientName: "Neha Verma",
    clientCompany: "WealthWise",
    clientType: "Startup",
    clientRating: 4.4,
    location: "Remote"
  },
  {
    id: 8,
    title: "Local SEO Specialist for Artisanal Bakery",
    category: "Marketing",
    budget: 10000,
    experienceLevel: "Beginner",
    description: "Help our local artisanal bakery, 'The Crusty Loaf', dominate local search results. We need someone to optimize our Google Business Profile, manage local citations, and perform on-page SEO for our website. You should also help us develop a strategy for gathering more customer reviews. The goal is to appear in the 'Local Pack' for keywords like 'best sourdough near me' and 'organic bakery Pune'.",
    postedDate: "2026-03-06",
    clientName: "Rahul Mehta",
    clientCompany: "The Crusty Loaf",
    clientType: "Individual",
    clientRating: 4.8,
    location: "Koregaon Park, Pune, India"
  },
  {
    id: 9,
    title: "Technical Documentation Specialist for Cloud API",
    category: "Writing",
    budget: 18000,
    experienceLevel: "Expert",
    description: "We need a technical writer to create exhaustive documentation for our new Cloud Storage API. This includes a comprehensive 'Getting Started' guide, detailed endpoint references, and code examples in multiple languages (Python, JS, Go). You should be able to read source code to understand functionality and work closely with our engineering team. Experience with tools like Swagger/OpenAPI and Markdown is essential.",
    postedDate: "2026-03-09",
    clientName: "Deepak Reddy",
    clientCompany: "SkyScale Cloud",
    clientType: "Enterprise",
    clientRating: 4.9,
    location: "Remote"
  },
  {
    id: 10,
    title: "Senior iOS Developer for Health & Wellness App",
    category: "Mobile Dev",
    budget: 35000,
    experienceLevel: "Intermediate",
    description: "Join our team to build out the next generation of our health tracking application. You will be implementing advanced features using Apple's HealthKit, including sleep analysis and heart rate variability tracking. The app is built entirely in SwiftUI and follows the MVVM architecture. You should have a strong eye for detail and a passion for creating smooth, native iOS experiences. Experience with Combine or Swift Concurrency is a plus.",
    postedDate: "2026-03-12",
    clientName: "Kavita Rao",
    clientCompany: "ZenLife Systems",
    clientType: "Startup",
    clientRating: 4.7,
    location: "Gachibowli, Hyderabad, India"
  },
  {
    id: 11,
    title: "Custom WordPress Developer for Media Portal",
    category: "Web Development",
    budget: 20000,
    experienceLevel: "Intermediate",
    description: "We are looking for a WordPress expert to revamp our high-traffic news portal. This involves creating a custom child theme, optimizing database queries for speed, and ensuring 100/100 Core Web Vitals scores. You should be proficient in PHP, JavaScript, and the Gutenberg block editor. The site needs to handle over 500k monthly visitors, so scalability and security are paramount.",
    postedDate: "2026-03-03",
    clientName: "Arjun Kapoor",
    clientCompany: "MetroNews Network",
    clientType: "Agency",
    clientRating: 4.6,
    location: "Remote"
  },
  {
    id: 12,
    title: "Junior Graphic Designer for E-commerce Assets",
    category: "Design",
    budget: 7000,
    experienceLevel: "Beginner",
    description: "We need a creative individual to help us produce a high volume of digital assets for our upcoming festive sale. This includes social media banners, email headers, and product display ads. You will be working with our existing brand guidelines but will have room to bring fresh ideas. Proficiency in Adobe Photoshop and Illustrator is required. This is a fast-paced project with tight deadlines.",
    postedDate: "2026-03-07",
    clientName: "Sneha Patil",
    clientCompany: "LuxeFashion",
    clientType: "Enterprise",
    clientRating: 4.3,
    location: "T. Nagar, Chennai, India"
  },
  {
    id: 13,
    title: "Klaviyo Email Marketing Automation Expert",
    category: "Marketing",
    budget: 30000,
    experienceLevel: "Expert",
    description: "Our D2C brand needs a sophisticated email marketing strategy to drive repeat purchases. You will be responsible for setting up advanced Klaviyo flows, including browse abandonment, post-purchase cross-sells, and win-back campaigns. You should also manage our weekly newsletter and perform A/B testing on subject lines and layouts. A proven track record of increasing email-attributed revenue is a must.",
    postedDate: "2026-03-10",
    clientName: "Manoj Bajpayee",
    clientCompany: "UrbanRoots",
    clientType: "Startup",
    clientRating: 4.9,
    location: "Remote"
  },
  {
    id: 14,
    title: "Lead Android Developer for Logistics App",
    category: "Mobile Dev",
    budget: 40000,
    experienceLevel: "Expert",
    description: "We are building a mission-critical application for our delivery fleet and need a lead Android developer. The app requires complex background processing for real-time GPS tracking, offline data synchronization, and a robust notification system. You should be an expert in Kotlin, Jetpack Compose, and Dagger/Hilt. Experience with Google Maps API and battery optimization is crucial for this role.",
    postedDate: "2026-03-11",
    clientName: "Pooja Hegde",
    clientCompany: "LogiTrack Solutions",
    clientType: "Enterprise",
    clientRating: 4.8,
    location: "Salt Lake, Kolkata, India"
  },
  {
    id: 15,
    title: "Direct Response Copywriter for Sales Funnel",
    category: "Writing",
    budget: 15000,
    experienceLevel: "Intermediate",
    description: "We need a copywriter who understands the psychology of selling. You will be writing the copy for a multi-step sales funnel for a premium coaching program. This includes the landing page, checkout page, and a 7-day email sequence. Your writing should be persuasive, empathetic, and focused on driving conversions. Please provide examples of previous sales copy that has performed well.",
    postedDate: "2026-03-01",
    clientName: "Rohan Joshi",
    clientCompany: "Peak Performance Coaching",
    clientType: "Individual",
    clientRating: 4.7,
    location: "Remote"
  },
  {
    id: 16,
    title: "Shopify Plus Developer for Brand Migration",
    category: "Web Development",
    budget: 22000,
    experienceLevel: "Intermediate",
    description: "Help us migrate our existing store to Shopify Plus. This involves theme customization using Liquid, setting up complex product variants, and integrating with our ERP system. You should have experience with Shopify's API and be able to build custom private apps if needed. Attention to detail in preserving SEO rankings during the migration is a top priority.",
    postedDate: "2026-03-04",
    clientName: "Aditi Rao",
    clientCompany: "EcoHome Decor",
    clientType: "Startup",
    clientRating: 4.5,
    location: "Remote"
  },
  {
    id: 17,
    title: "Professional Illustrator for Children's Series",
    category: "Design",
    budget: 30000,
    experienceLevel: "Expert",
    description: "We are looking for a long-term partner to illustrate a new series of children's books. The first book requires 15 full-page, high-detail illustrations in a whimsical, hand-drawn style. You should be able to create consistent characters and vibrant environments. This project requires multiple rounds of sketches and revisions to ensure the vision is perfectly captured.",
    postedDate: "2026-03-06",
    clientName: "Siddharth Malhotra",
    clientCompany: "DreamWeaver Publishing",
    clientType: "Agency",
    clientRating: 5.0,
    location: "Remote"
  },
  {
    id: 18,
    title: "Performance Marketing / Google Ads Specialist",
    category: "Marketing",
    budget: 15000,
    experienceLevel: "Intermediate",
    description: "Our B2B SaaS company needs help scaling our Google Ads campaigns. We are currently seeing high CPAs and need an expert to audit our account, restructure campaigns, and optimize our bidding strategy. You will be responsible for keyword expansion, negative keyword management, and ad copy testing. Weekly reporting on key metrics like ROAS and conversion rate is expected.",
    postedDate: "2026-03-08",
    clientName: "Kriti Sanon",
    clientCompany: "SaaSFlow",
    clientType: "Startup",
    clientRating: 4.6,
    location: "Cyber City, Gurgaon, India"
  },
  {
    id: 19,
    title: "Ghostwriter for Thought Leadership Ebook",
    category: "Writing",
    budget: 40000,
    experienceLevel: "Expert",
    description: "I am a CEO in the tech space looking for a ghostwriter to help me finish an ebook on 'The Future of Remote Work'. I have the outline and several hours of recorded interviews ready. Your job is to synthesize this information into a compelling, 50-page narrative that sounds like me. You should have experience writing for a business audience and be able to handle complex topics with ease.",
    postedDate: "2026-03-12",
    clientName: "Varun Dhawan",
    clientCompany: "Dhawan Ventures",
    clientType: "Individual",
    clientRating: 4.9,
    location: "Remote"
  },
  {
    id: 20,
    title: "Flutter Developer for Social Networking MVP",
    category: "Mobile Dev",
    budget: 28000,
    experienceLevel: "Intermediate",
    description: "We are building a niche social networking app and need a Flutter developer to build our MVP. The app includes features like user profiles, a dynamic news feed, real-time chat (using Firebase), and push notifications. You should be proficient in state management (Riverpod or Bloc) and have experience building responsive UIs that look great on both iOS and Android.",
    postedDate: "2026-03-13",
    clientName: "Alia Bhatt",
    clientCompany: "Connectify",
    clientType: "Startup",
    clientRating: 4.7,
    location: "Bandra West, Mumbai, India"
  },
  {
    id: 21,
    title: "Python Developer for Advanced Web Scraping",
    category: "Web Development",
    budget: 12000,
    experienceLevel: "Beginner",
    description: "We need a Python script to collect pricing data from several competitor websites on a daily basis. The script needs to handle dynamic content (JavaScript rendering), bypass basic bot detection, and output the data to a clean, structured CSV file. You should be familiar with libraries like BeautifulSoup, Selenium, or Playwright. Clean, well-documented code is a must.",
    postedDate: "2026-03-13",
    clientName: "Ranbir Kapoor",
    clientCompany: "DataMines",
    clientType: "Startup",
    clientRating: 4.8,
    location: "Remote"
  }
];
